--- #YAML:1.0
name: Image-Magick-Chart
version: 1.02
author:
  - Ron Savage <ron@savage.net.au>
abstract: Use Image::Magick to create charts.
license: artistic
requires:
  Carp: 0
  Image::Magick: 6
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  Image::Magick::Chart:
    file: lib/Image/Magick/Chart.pm
    version: 1.02
  Image::Magick::Chart::HorizontalBars:
    file: lib/Image/Magick/Chart/HorizontalBars.pm
    version: 1.02
generated_by: Module::Build version 0.2611
